name: Cypress Tests

on:
  schedule:
    - cron: '0 17 * * 0' # Автозапуск щонеділі о 17:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run --browser ${{ matrix.browser }}